### ISSUE TITLE
onNotification doesnt get called

### ISSUE THREAD

**Issue by denigada** [MatthieuLemoine/push-receiver#14]
Hello, I am using this in my nw.js desktop app. Thank you a lot for this library it saved my life.

My onNotification function does not get called when I send a notification. I could not figure out how to solve this issue. Can you please help me ? Here is my code:

![unknown](https://user-images.githubusercontent.com/5206952/36646302-f0ebf6bc-1a43-11e8-8dd6-3f20cf9dbf23.png)

I call initNotifications if there is no credentials stored and retrieveNotifications if there are. Thank you so much in advance.

**Comment by MatthieuLemoine** [comment]
@denigada Your code seems fine. Can you clone the project and try the example in `example/index.js` ?
