### ISSUE TITLE
hide application name in notification

### ISSUE THREAD

**Issue by denigada** [MatthieuLemoine/push-receiver#15]
Hello. When Im showing the notification with this code:

`let myNotification = new Notification(notification.data.title, { body: notification.data.body });`

It prints this:
![screen shot 2018-03-18 at 2 23 38 pm](https://user-images.githubusercontent.com/5206952/37569390-fdbb408a-2ab7-11e8-97b5-0888e71138ed.png)

How can I remove that app name "electron-quick-start" from the notification?

**Comment by MatthieuLemoine** [comment]
Hi @denigada, the `Notification` API is an electron/nwjs API. It has nothing to do with this library. You can find more informations in electron/nwjs documentations.
