### ISSUE TITLE
Can this be used by CefSharp?

### ISSUE THREAD

**Issue by luiscla27** [MatthieuLemoine/push-receiver#29]
CefSharp also uses Chronium bases, can this be used by [CefSharp](https://cefsharp.github.io/)?

**Comment by MatthieuLemoine** [comment]
@luiscla27 You don't need Chromium. I reversed engineered Chromium to find a way to receive FCM push notifications in a Node.js application. Therefore the only thing you need to use push-receiver is Node.js.

I don't know CefSharp but from what I can see in its home page, unlike Electron, it doesn't seem to be able to run a Node.js application.

Therefore I would say no 😕
