### ISSUE TITLE
"Error: read ECONNRESET" messages in the console

### ISSUE THREAD

**Issue by eschava** [MatthieuLemoine/push-receiver#33]
A message like below is printed ~ every 30 minutes to the console (internet connection is stable)
Is there a way to keep console clean?

```
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:200:27) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read' 
} 
```

**Comment by GitNomster** [comment]
I have same problem on electron 7.1.13 win10 x64.

**Comment by realjax** [comment]
Same problem.

**Comment by realjax** [comment]
I created a PR to 'fix' this.
